HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2018 — 2020"
      institution: "Banepa NIST"
      description: "NEB +2 Science"
    - period: "2021 — 2025"
      institution: "Kantipur Engineering College"
      description: "Bachelor's in Computer Engineering"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2024 — Present"
      position: "Data Fellow"
      description: "CodeForNepal"
    - period: "2024 — 2024"
      position: "AWS Fellow"
      description: "AWS Cloud Club Nepal - 2 Months"

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: false
  label: "Languages"
  items:
    - language: "English"
      proficiency: "70%"
    - language: "Nepali"
      proficiency: "60%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: false
  label: "My Skills"
  items:
    - skill: "Web Development"
      proficiency: "60%"
    - skill: "Data Science"
      proficiency: "50%"
